<template>
  <div class="loadingio-spinner-bean-eater-jgedosk6b7t">
    <div class="ldio-43iemof1ylg">
      <div>
        <div></div>
        <div></div>
        <div></div>
      </div>
      <div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-43iemof1ylg-1 {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(-45deg);
  }
  100% {
    transform: rotate(0deg);
  }
}
@keyframes ldio-43iemof1ylg-2 {
  0% {
    transform: rotate(180deg);
  }
  50% {
    transform: rotate(225deg);
  }
  100% {
    transform: rotate(180deg);
  }
}
.ldio-43iemof1ylg > div:nth-child(2) {
  transform: translate(-15px, 0);
}
.ldio-43iemof1ylg > div:nth-child(2) div {
  position: absolute;
  top: 40px;
  left: 40px;
  width: 120px;
  height: 60px;
  border-radius: 120px 120px 0 0;
  background: #f8b26a;
  animation: ldio-43iemof1ylg-1 1s linear infinite;
  transform-origin: 60px 60px;
}
.ldio-43iemof1ylg > div:nth-child(2) div:nth-child(2) {
  animation: ldio-43iemof1ylg-2 1s linear infinite;
}
.ldio-43iemof1ylg > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}
@keyframes ldio-43iemof1ylg-3 {
  0% {
    transform: translate(190px, 0);
    opacity: 0;
  }
  20% {
    opacity: 1;
  }
  100% {
    transform: translate(70px, 0);
    opacity: 1;
  }
}
.ldio-43iemof1ylg > div:nth-child(1) {
  display: block;
}
.ldio-43iemof1ylg > div:nth-child(1) div {
  position: absolute;
  top: 92px;
  left: -8px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #e15b64;
  animation: ldio-43iemof1ylg-3 1s linear infinite;
}
.ldio-43iemof1ylg > div:nth-child(1) div:nth-child(1) {
  animation-delay: -0.67s;
}
.ldio-43iemof1ylg > div:nth-child(1) div:nth-child(2) {
  animation-delay: -0.33s;
}
.ldio-43iemof1ylg > div:nth-child(1) div:nth-child(3) {
  animation-delay: 0s;
}
.loadingio-spinner-bean-eater-jgedosk6b7t {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}
.ldio-43iemof1ylg {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-43iemof1ylg div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
